version: '3.8'

services:

  backoffice:
    container_name: product-backoffice
    build:
      context: product/backoffice/
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - inner_network
    volumes:
      - ./config/local.yml:/app/local.yml
      - ./product/backoffice/src/main/resources/application.yml:/app/product/backoffice/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/local.yml,file:/app/product/backoffice/application.yml

  conference:
    container_name: product-conference
    build:
      context: product/conference/
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - inner_network
    volumes:
      - ./config/local.yml:/app/local.yml
      - ./product/conference/src/main/resources/application.yml:/app/product/conference/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/local.yml,file:/app/product/conference/application.yml
    depends_on:
      - backoffice

networks:
  inner_network:
    name: inner_network
    ipam:
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1