spring:
  flyway:
    schemas: conference
  jpa:
    properties:
      hibernate:
        default_schema: conference

springdoc:
  info:
    title: "API Documentation"
    description: "For Conference module"
    version: "1.0.0"